name: Deploy Hexo Blog

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: 安装 Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: 安装依赖
        run: npm install

      - name: 构建站点
        run: npx hexo clean && npx hexo generate

      - name: 发布到 gh-pages 分支
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
